project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "EDA of Behavioral Risk Analysis of Nutrition, Physical Health and Obesity"
  author:
    - Tushar Prasad (tp2802)
    - Anusree Mondal Rakhi (ar4636)
  repo-url: https://github.com/tusharprasad512/BehavioralRiskEDAV
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


